[project]
name = "generate"
version = "0.1.0"
description = "New Lean benchmark for real-world SWE tasks"
readme = "README.md"
authors = [
    { name = "Quinn Dougherty", email = "quinn.dougherty.forall@gmail.com" },
    { name = "Hazel Shackleton", email = "hazel.shackleton@galois.com" }
]
requires-python = ">=3.13"
dependencies = [
    "codegen>=0.57.0",
    "datasets>=4.1.1",
    "hvplot>=0.12.1",
    "inspect-ai>=0.3.140",
    "jinja2>=3.1.6",
    "jsonlines>=4.0.0",
    "mcp>=1.18.0",
    "pandas>=2.3.3",
    "panel>=1.8.2",
    "pydantic>=2.12.3",
    "pydantic-ai>=1.2.1",
    "python-dotenv>=1.1.1",
    "rich>=13.9.4",
    "streamlit>=1.50.0",
    "tqdm>=4.67.1",
    "trio>=0.31.0",
    "typer>=0.19.2",
    "wandb>=0.22.2",
]

[project.scripts]
preview_prompts = "generate.templates:main"
fvspec = "generate:main"
analyze_deps_regex = "scripts.analyze_deps_regex:cli"
analyze_deps = "scripts.analyze_deps:main"

[project.entry-points.inspect_ai]
benchmark = "generate._registry"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::pydantic.warnings.UnsupportedFieldAttributeWarning",  # source unconfirmed, possibly introduced by wandb dependency
]

[tool.ruff.lint]
select = ["D"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[build-system]
requires = ["uv_build>=0.8.2,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "hypothesis>=6.140.3",
    "pytest>=8.4.2",
    "pytest-mock>=3.15.1",
    "ruff>=0.14.0",
    "ty>=0.0.1a21",
]
