[project]
name = "dashboard"
version = "0.1.0"
description = "Dashboard for viewing benchmark metrics interactively."
readme = "README.md"
authors = [
    { name = "Hazel Shackleton", email = "hazel.shackleton@galois.com" }
]
requires-python = ">=3.13"
dependencies = [
    "panel",
    "hvplot",
    "pandas",
]

[project.scripts]

[build-system]
requires = ["uv_build>=0.8.2,<0.9.0"]
build-backend = "uv_build"
